### ISSUE TITLE
Pyroms-scrip could not be imported. Remapping functions will not be available 

### ISSUE THREAD

**Issue by sameerCoder** [hadfieldnz/roms-scripts-mgh#1]
Hi @hadfieldnz 
I am trying to create Initial condition and boundary condition using Pyroms and after installing scrip as suggested by pyroms readme file, scrip got installed successfully but then also i am facing issue in Remapping function,
Can you help me on this please,
I am getting below Error : 
```
import pyroms
WARNING:root: scrip could not be imported. Remapping functions will not be available
(pyroms1) username@username-Desktop:~/Desktop/org_pyroms/examples/Yellow_Sea/Inputs/Initial$ python3 make_remap_weights_file.py
WARNING:root: scrip could not be imported. Remapping functions will not be available

printing lon_t 2
lont shape (330, 720)
yrange: 190
y 240
Assuming spherical is integer b'T' <class 'numpy.ma.core.MaskedArray'>
Load geographical grid from file
grid shape 122 142
grid shape 122 141
grid shape 121 142
Traceback (most recent call last):
File "make_remap_weights_file.py", line 27, in
pyroms.remapping.compute_remap_weights(grid1_file, grid2_file,
File "/home/username/python_learn_24feb2021/pyroms/pyroms/pyroms/remapping/compute_remap_weights.py", line 41, in compute_remap_weights
pyroms.remapping.scrip.compute_remap_weights('compute_remap_weights_in')
AttributeError: module 'pyroms.remapping' has no attribute 'scrip'
(pyroms1) username@username-Desktop:~/Desktop/org_pyroms/examples/Yellow_Sea/Inputs/Initial$ python
Python 3.8.5 (default, Sep 4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.

import pyroms
WARNING:root: scrip could not be imported. Remapping functions will not be available
print(dir(pyroms.remapping))
['builtins', 'cached', 'doc', 'file', 'loader', 'name', 'package', 'path', 'spec', 'compute_remap_weights', 'flood', 'flood2d', 'logging', 'make_remap_grid_file', 'remap', 'remap2', 'roms2z', 'sta2z', 'test_remap_weights', 'z2roms']
```
For more detail you can please visit below link
https://github.com/ESMG/pyroms/issues/32

I will really appreciate if any help.
Thank you.

**Comment by YoungEnzo** [comment]
hello, bro, I encountered the same error with you :
**AttributeError: module 'pyroms.remapping' has no attribute 'scrip'**
although, I think I have already successfully installed the SCRIP... Have you solved it yet?

**Comment by aswathy121** [comment]
hello, I also encountered the same error with you :
AttributeError: module 'pyroms.remapping' has no attribute 'scrip'

Have you solved it yet?
Could you please help?

Thank you
